apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: null
  generation: 4
  labels:
    app: superset
    release: insights-a  
    app.kubernetes.io/name: {{ include "fiq-insights-superset.fullname" . }}
  name: {{ include "fiq-insights-superset.fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: superset
      release: insights-a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/secrets: 13188d8d682bead91edbb2dd1a7202148cd614e62b61b686a6d5f787272f65e3
      creationTimestamp: null
      labels:
        app: superset
        release: insights-a
        app.kubernetes.io/name: {{ include "fiq-insights-superset.fullname" . }}
      name: insights-a-superset
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 4 }}
    {{- end }}
      containers:
      - args:
        - /fiq-init.sh
        command:
        - /bin/bash
        image:  "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: superset
        ports:
        - containerPort: 8088
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        {{- with .Values.imagePullSecrets }}
        resources:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/superset
          name: superset-configs
        - mountPath: /var/lib/superset
          name: storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: superset-configs
        secret:
          defaultMode: 420
          secretName: insights-a-superset
      - name: storage-volume
        persistentVolumeClaim:
          claimName: insights-a-superset
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: superset
    release: insights-a
    app.kubernetes.io/name: {{ include "fiq-insights-superset.fullname" . }}
  name: {{ include "fiq-insights-superset.fullname" . }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8088
  selector:
    app: superset
    release: insights-a
  sessionAffinity: None
  type: {{ .Values.service.type }}
